import Head from "next/head";
import Header from "@/components/header";
import Footer from "@/components/footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header Styling dengan CSS Moduls */}
      <Header />

      {/* Content Styling dengan Global CSS */}
      <p className="content">Content</p>

      {/* Footer Styling dengan Tailwind CSS */}
      <Footer />
    </>
  );
}
